"""Governed editorial-relation contracts for Increment 2 and Increment 4."""

from .fixture_v2 import (
    INTEGRATED_FIXTURE_V2,
    INTEGRATED_FIXTURE_V2_BINDING_ID,
    INTEGRATED_FIXTURE_V2_DIGEST,
    IntegratedFixtureV2,
    IntegratedFixtureV2Passage,
    IntegratedFixtureV2RelationTemplate,
    load_integrated_fixture_v2,
)
from .models import (
    FixturePassageLifecycleLink,
    FixturePassageObject,
    IntegratedFixtureV2Binding,
    IntegratedFixtureV2BindingId,
    IntegratedFixtureV2BindingRequest,
    RelationAdmissionDecision,
    RelationAdmissionDecisionId,
    RelationAssertion,
    RelationAssertionId,
    RelationAuthorityError,
    RelationConflict,
    RelationContractError,
    RelationCurrentState,
    RelationDecisionAction,
    RelationDecisionRequest,
    RelationDecisionResult,
    RelationEndpoint,
    RelationPredicate,
    RelationProducer,
    RelationProducerKind,
    RelationProjectionAction,
    RelationProjectionEvent,
    RelationProposal,
    RelationProposalId,
    RelationProposalRequest,
    RelationReadPolicy,
    RelationRecordType,
    RelationSemanticCollision,
    RelationStaleDecision,
    RelationStateError,
    RelationTemporalScope,
    governed_relation_key,
    sorted_passage_objects,
)
from .policy import (
    INTEGRATED_FIXTURE_V2_BIND_COMMAND,
    RELATION_COMMAND_TYPES,
    RELATION_DECISION_COMMAND,
    RELATION_PROPOSAL_COMMAND,
    merge_relation_authority_registries,
    relation_command_definitions,
    relation_payload_contracts,
)
from .traceability import (
    INCREMENT_2A_DEFERRED,
    INCREMENT_2A_EXCLUSIONS,
    INCREMENT_2A_TRACEABILITY,
)

_AUTHORITY_FACADE_NAMES = {
    "GovernedRelationAuthoritySystem",
    "GovernedRelations",
    "open_governed_relation_authority_system",
}

_EDITORIAL_MODEL_NAMES = {
    "CanonicalEntityRelationEndpoint",
    "EDITORIAL_PREDICATE_REGISTRY_V1",
    "EditorialPredicateContract",
    "EditorialPredicateEndpointPair",
    "EditorialPredicateRegistry",
    "EditorialRelationAssertion",
    "EditorialRelationCurrentView",
    "EditorialRelationDecision",
    "EditorialRelationDecisionRequest",
    "EditorialRelationEndpoint",
    "EditorialRelationEvidence",
    "EditorialRelationProducer",
    "EditorialRelationProjectionEvent",
    "EditorialRelationProposal",
    "EditorialRelationProposalRequest",
    "EditorialRelationProposalVersion",
    "EditorialRelationReadPolicy",
    "EditorialRelationTemporalScope",
    "EventHypothesisRelationEndpoint",
    "ExtractionRelationEvidence",
    "RelationAssertionRelationEndpoint",
    "SourceRevisionRelationEndpoint",
    "StoryCandidateRelationEndpoint",
}

_EDITORIAL_POLICY_NAMES = {
    "EDITORIAL_RELATION_COMMAND_TYPES",
    "EDITORIAL_RELATION_DECISION_COMMAND",
    "EDITORIAL_RELATION_PROPOSAL_COMMAND",
    "editorial_relation_command_definitions",
    "editorial_relation_payload_contracts",
    "merge_editorial_relation_authority_registries",
}

_EDITORIAL_TYPE_NAMES = {
    "EditorialPredicateCode",
    "EditorialPredicateDirectionality",
    "EditorialPredicateTemporalSemantics",
    "EditorialRelationAssertionId",
    "EditorialRelationAssertionLifecycle",
    "EditorialRelationAuthorityError",
    "EditorialRelationContractError",
    "EditorialRelationCurrentState",
    "EditorialRelationDecisionAction",
    "EditorialRelationDecisionConflict",
    "EditorialRelationDecisionId",
    "EditorialRelationEndpointKind",
    "EditorialRelationEvidenceKind",
    "EditorialRelationIdentifierReuse",
    "EditorialRelationProducerKind",
    "EditorialRelationProjectionAction",
    "EditorialRelationProposalId",
    "EditorialRelationProposalVersionId",
    "EditorialRelationRightsDenied",
    "EditorialRelationSemanticCollision",
    "EditorialRelationStaleDecision",
    "EditorialRelationStateError",
    "EditorialRelationSupersessionId",
}

def __getattr__(name: str):
    if name in _AUTHORITY_FACADE_NAMES:
        from newsroom.authority import relation_system as _system

        return getattr(_system, name)
    if name in _EDITORIAL_MODEL_NAMES:
        from . import editorial_models as _editorial_models

        return getattr(_editorial_models, name)
    if name in _EDITORIAL_POLICY_NAMES:
        from . import editorial_policy as _editorial_policy

        return getattr(_editorial_policy, name)
    if name in _EDITORIAL_TYPE_NAMES:
        from . import editorial_types as _editorial_types

        return getattr(_editorial_types, name)
    raise AttributeError(name)


__all__ = [
    "CanonicalEntityRelationEndpoint",
    "EDITORIAL_PREDICATE_REGISTRY_V1",
    "EDITORIAL_RELATION_COMMAND_TYPES",
    "EDITORIAL_RELATION_DECISION_COMMAND",
    "EDITORIAL_RELATION_PROPOSAL_COMMAND",
    "EditorialPredicateCode",
    "EditorialPredicateContract",
    "EditorialPredicateDirectionality",
    "EditorialPredicateEndpointPair",
    "EditorialPredicateRegistry",
    "EditorialPredicateTemporalSemantics",
    "EditorialRelationAssertionLifecycle",
    "EditorialRelationCurrentView",
    "EditorialRelationDecision",
    "EditorialRelationDecisionAction",
    "EditorialRelationDecisionConflict",
    "EditorialRelationDecisionId",
    "EditorialRelationEvidence",
    "EditorialRelationEvidenceKind",
    "EditorialRelationIdentifierReuse",
    "EditorialRelationProducer",
    "EditorialRelationProducerKind",
    "EditorialRelationProposalVersion",
    "EditorialRelationProposalVersionId",
    "EditorialRelationRightsDenied",
    "EditorialRelationSemanticCollision",
    "EditorialRelationStaleDecision",
    "EditorialRelationSupersessionId",
    "EventHypothesisRelationEndpoint",
    "ExtractionRelationEvidence",
    "EditorialRelationAssertion",
    "EditorialRelationAssertionId",
    "EditorialRelationAuthorityError",
    "EditorialRelationContractError",
    "EditorialRelationCurrentState",
    "EditorialRelationEndpoint",
    "EditorialRelationProjectionAction",
    "EditorialRelationProjectionEvent",
    "EditorialRelationProposal",
    "EditorialRelationProposalId",
    "EditorialRelationProposalRequest",
    "EditorialRelationReadPolicy",
    "EditorialRelationStateError",
    "EditorialRelationTemporalScope",
    "RelationAssertionRelationEndpoint",
    "SourceRevisionRelationEndpoint",
    "StoryCandidateRelationEndpoint",
    "editorial_relation_command_definitions",
    "editorial_relation_payload_contracts",
    "merge_editorial_relation_authority_registries",
    "FixturePassageLifecycleLink",
    "FixturePassageObject",
    "GovernedRelationAuthoritySystem",
    "GovernedRelations",
    "INTEGRATED_FIXTURE_V2",
    "INTEGRATED_FIXTURE_V2_BINDING_ID",
    "INTEGRATED_FIXTURE_V2_BIND_COMMAND",
    "INTEGRATED_FIXTURE_V2_DIGEST",
    "INCREMENT_2A_DEFERRED",
    "INCREMENT_2A_EXCLUSIONS",
    "INCREMENT_2A_TRACEABILITY",
    "IntegratedFixtureV2",
    "IntegratedFixtureV2Binding",
    "IntegratedFixtureV2BindingId",
    "IntegratedFixtureV2BindingRequest",
    "IntegratedFixtureV2Passage",
    "IntegratedFixtureV2RelationTemplate",
    "RELATION_COMMAND_TYPES",
    "RELATION_DECISION_COMMAND",
    "RELATION_PROPOSAL_COMMAND",
    "RelationAdmissionDecision",
    "RelationAdmissionDecisionId",
    "RelationAssertion",
    "RelationAssertionId",
    "RelationAuthorityError",
    "RelationConflict",
    "RelationContractError",
    "RelationCurrentState",
    "RelationDecisionAction",
    "RelationDecisionRequest",
    "RelationDecisionResult",
    "RelationEndpoint",
    "RelationPredicate",
    "RelationProducer",
    "RelationProducerKind",
    "RelationProjectionAction",
    "RelationProjectionEvent",
    "RelationProposal",
    "RelationProposalId",
    "RelationProposalRequest",
    "RelationReadPolicy",
    "RelationRecordType",
    "RelationSemanticCollision",
    "RelationStaleDecision",
    "RelationStateError",
    "RelationTemporalScope",
    "governed_relation_key",
    "load_integrated_fixture_v2",
    "merge_relation_authority_registries",
    "open_governed_relation_authority_system",
    "relation_command_definitions",
    "relation_payload_contracts",
    "sorted_passage_objects",
]
