"""Deterministic Discovery Signal, gate, and News Lead contracts."""

from .models import (
    DiscoverySignalRequest,
    GateDecisionRequest,
    LeadDispositionDecisionRequest,
    NewsLeadRequest,
    WatchConditionRequest,
)
from .record_models import (
    DiscoverySignal,
    GateDecision,
    LeadDispositionDecision,
    NewsLead,
    WatchCondition,
)
from .types import (
    ACTIVE_INCREMENT_3D_DISPOSITIONS,
    DecisionTerminality,
    DiscoveryAuthorityError,
    DiscoveryContractError,
    DiscoveryIdentifierReuse,
    DiscoveryReadPolicy,
    DiscoverySemanticCollision,
    DiscoverySignalId,
    DiscoveryStateError,
    DiscoveryVersionConflict,
    GateBasis,
    GateDecisionId,
    GateOutcome,
    LeadDispositionDecisionId,
    LeadDispositionOutcome,
    NewsLeadId,
    NextAction,
    NextActionKind,
    ObservableNewness,
    ReasonBasisClass,
    ReasonReference,
    ScopeDisposition,
    StructuredReason,
    TimeValidity,
    UrgencyBasis,
    UrgencyRoute,
    WatchConditionId,
)

__all__ = [
    "ACTIVE_INCREMENT_3D_DISPOSITIONS",
    "DecisionTerminality",
    "DiscoveryAuthorityError",
    "DiscoveryContractError",
    "DiscoveryIdentifierReuse",
    "DiscoveryReadPolicy",
    "DiscoverySemanticCollision",
    "DiscoverySignal",
    "DiscoverySignalId",
    "DiscoverySignalRequest",
    "DiscoveryStateError",
    "DiscoveryVersionConflict",
    "GateBasis",
    "GateDecision",
    "GateDecisionId",
    "GateDecisionRequest",
    "GateOutcome",
    "LeadDispositionDecision",
    "LeadDispositionDecisionId",
    "LeadDispositionDecisionRequest",
    "LeadDispositionOutcome",
    "NewsLead",
    "NewsLeadId",
    "NewsLeadRequest",
    "NextAction",
    "NextActionKind",
    "ObservableNewness",
    "ReasonBasisClass",
    "ReasonReference",
    "ScopeDisposition",
    "StructuredReason",
    "TimeValidity",
    "UrgencyBasis",
    "UrgencyRoute",
    "WatchCondition",
    "WatchConditionId",
    "WatchConditionRequest",
]

from .payloads import (
    discovery_signal_payload,
    gate_decision_payload,
    lead_disposition_payload,
    news_lead_payload,
    watch_condition_payload,
)
from .policy import (
    DISCOVERY_GATE_DECIDE_COMMAND,
    DISCOVERY_LEAD_DISPOSITION_RECORD_COMMAND,
    DISCOVERY_LEAD_OPEN_COMMAND,
    DISCOVERY_SIGNAL_ADMIT_COMMAND,
    DISCOVERY_SIGNAL_LEAD_COMMAND_TYPES,
    DISCOVERY_WATCH_CONDITION_RECORD_COMMAND,
    discovery_signal_lead_command_definitions,
    discovery_signal_lead_payload_contracts,
    merge_discovery_signal_lead_registries,
)

__all__ += [
    "DISCOVERY_GATE_DECIDE_COMMAND",
    "DISCOVERY_LEAD_DISPOSITION_RECORD_COMMAND",
    "DISCOVERY_LEAD_OPEN_COMMAND",
    "DISCOVERY_SIGNAL_ADMIT_COMMAND",
    "DISCOVERY_SIGNAL_LEAD_COMMAND_TYPES",
    "DISCOVERY_WATCH_CONDITION_RECORD_COMMAND",
    "discovery_signal_lead_command_definitions",
    "discovery_signal_lead_payload_contracts",
    "discovery_signal_payload",
    "gate_decision_payload",
    "lead_disposition_payload",
    "merge_discovery_signal_lead_registries",
    "news_lead_payload",
    "watch_condition_payload",
]
