"""Governed source-registry contracts for Increment 3A."""

from .models import (
    DiscoveryOccurrence,
    DiscoveryOccurrenceRequest,
    DiscoveryRepresentation,
    DiscoveryRepresentationRequest,
    LocatorContinuityDecision,
    LocatorContinuityDecisionRequest,
    SourceDefinition,
    SourceDefinitionRequest,
    SourceDefinitionVersion,
    SourceDefinitionVersionRequest,
    SourceDefinitionVersionSummary,
    SourceItem,
    SourceItemRequest,
    SourceRevision,
    SourceRevisionRequest,
)
from .policy import (
    DISCOVERY_OCCURRENCE_RECORD_COMMAND,
    DISCOVERY_REPRESENTATION_RECORD_COMMAND,
    SOURCE_DEFINITION_REGISTER_COMMAND,
    SOURCE_DEFINITION_VERSION_RECORD_COMMAND,
    SOURCE_ITEM_REGISTER_COMMAND,
    SOURCE_LOCATOR_CONTINUITY_DECIDE_COMMAND,
    SOURCE_REGISTRY_COMMAND_TYPES,
    SOURCE_REVISION_RECORD_COMMAND,
    merge_source_registry_authority_registries,
    source_registry_command_definitions,
    source_registry_payload_contracts,
)
from .traceability import (
    INCREMENT_3A_DEFERRED,
    INCREMENT_3A_EXCLUSIONS,
    INCREMENT_3A_TRACEABILITY,
)
from .types import (
    BaselinePolicy,
    BaselinePolicyKind,
    CheckOutcomeId,
    CoverageContribution,
    CoverageMapping,
    CoverageResponsibility,
    DiscoveryOccurrenceId,
    DiscoveryOccurrenceKind,
    DiscoveryRepresentationId,
    EXECUTION_AUTHORITY_DISABLED,
    ExplicitSourceGap,
    IdentityComponent,
    LocatorContinuityDecisionId,
    LocatorContinuityOutcome,
    ObservationModel,
    PortfolioFunction,
    RightsReference,
    SourceAuthorityError,
    SourceContractError,
    SourceDefinitionId,
    SourceDefinitionVersionId,
    SourceDependency,
    SourceDependencyKind,
    SourceIdentifierReuse,
    SourceItemId,
    SourceItemIdentityKind,
    SourceLifecycleStage,
    SourceRegistryReadPolicy,
    SourceRevisionId,
    SourceRole,
    SourceRoleAssignment,
    SourceSemanticCollision,
    SourceStateError,
    SourceTime,
    SourceVersionConflict,
    VersionedPolicyRef,
    sorted_coverage_mappings,
    sorted_dependencies,
    sorted_identity_components,
    sorted_role_assignments,
    sorted_source_gaps,
)

_AUTHORITY_FACADE_NAMES = {
    "GovernedSourceRegistryAuthoritySystem",
    "GovernedSources",
    "open_governed_source_registry_authority_system",
}


def __getattr__(name: str):
    if name in _AUTHORITY_FACADE_NAMES:
        from newsroom.authority import source_registry_system as _system

        return getattr(_system, name)
    raise AttributeError(name)


__all__ = [
    "BaselinePolicy",
    "BaselinePolicyKind",
    "CheckOutcomeId",
    "CoverageContribution",
    "CoverageMapping",
    "CoverageResponsibility",
    "DISCOVERY_OCCURRENCE_RECORD_COMMAND",
    "DISCOVERY_REPRESENTATION_RECORD_COMMAND",
    "DiscoveryOccurrence",
    "DiscoveryOccurrenceId",
    "DiscoveryOccurrenceKind",
    "DiscoveryOccurrenceRequest",
    "DiscoveryRepresentation",
    "DiscoveryRepresentationId",
    "DiscoveryRepresentationRequest",
    "EXECUTION_AUTHORITY_DISABLED",
    "ExplicitSourceGap",
    "GovernedSourceRegistryAuthoritySystem",
    "GovernedSources",
    "INCREMENT_3A_DEFERRED",
    "INCREMENT_3A_EXCLUSIONS",
    "INCREMENT_3A_TRACEABILITY",
    "IdentityComponent",
    "LocatorContinuityDecision",
    "LocatorContinuityDecisionId",
    "LocatorContinuityDecisionRequest",
    "LocatorContinuityOutcome",
    "ObservationModel",
    "PortfolioFunction",
    "RightsReference",
    "SOURCE_DEFINITION_REGISTER_COMMAND",
    "SOURCE_DEFINITION_VERSION_RECORD_COMMAND",
    "SOURCE_ITEM_REGISTER_COMMAND",
    "SOURCE_LOCATOR_CONTINUITY_DECIDE_COMMAND",
    "SOURCE_REGISTRY_COMMAND_TYPES",
    "SOURCE_REVISION_RECORD_COMMAND",
    "SourceAuthorityError",
    "SourceContractError",
    "SourceDefinition",
    "SourceDefinitionId",
    "SourceDefinitionRequest",
    "SourceDefinitionVersion",
    "SourceDefinitionVersionId",
    "SourceDefinitionVersionRequest",
    "SourceDefinitionVersionSummary",
    "SourceDependency",
    "SourceDependencyKind",
    "SourceIdentifierReuse",
    "SourceItem",
    "SourceItemId",
    "SourceItemIdentityKind",
    "SourceItemRequest",
    "SourceLifecycleStage",
    "SourceRegistryReadPolicy",
    "SourceRevision",
    "SourceRevisionId",
    "SourceRevisionRequest",
    "SourceRole",
    "SourceRoleAssignment",
    "SourceSemanticCollision",
    "SourceStateError",
    "SourceTime",
    "SourceVersionConflict",
    "VersionedPolicyRef",
    "merge_source_registry_authority_registries",
    "open_governed_source_registry_authority_system",
    "sorted_coverage_mappings",
    "sorted_dependencies",
    "sorted_identity_components",
    "sorted_role_assignments",
    "sorted_source_gaps",
    "source_registry_command_definitions",
    "source_registry_payload_contracts",
]
