"""Public authority contracts for Increment 1A1 and Increment 1A2a.

Mutation-capable SQLite persistence, authentication contexts, authorization
records, commit capabilities and retained payload bytes remain internal. Public
application code receives authenticated command and policy-bound metadata
facades only.
"""

from .auth import (
    AuthenticationError,
    AuthenticationProof,
    AuthorizationDenied,
    StaticAuthenticator,
    StaticAuthorizer,
    StaticPrincipal,
)
from .canonical import (
    CanonicalizationError,
    canonical_json_bytes,
    digest_bytes,
    digest_canonical,
    validate_sha256_digest,
)
from .models import (
    CommandDefinition,
    CommandValidationError,
    CommittedCommandIdentity,
    InlinePayload,
    NO_PAYLOAD,
    NoPayload,
    ObjectAdmissionDescriptor,
    ObjectAdmissionPayload,
    SemanticCommand,
)
from .persistence import (
    AuthenticationContextRecord,
    AuthorityCommands,
    AuthorityEvents,
    AuthorityPersistenceError,
    AuthoritySchemaError,
    AuthorityWriterBusy,
    AuthorizationDecisionRecord,
    AuthorizationRequestRecord,
    CommandDefinitionRecord,
    CommandResultRecord,
    CommittedCommand,
    EventProvenanceRecord,
    EventReadPolicy,
    ExpectedVersionConflict,
    IdempotencyConflict,
    LedgerEventRecord,
    MetadataClass,
    PayloadId,
    PayloadSchemaContractRecord,
    ReadPolicyDenied,
    SUCCESSFUL_READ_AUDIT_STATUS,
    UnknownCausation,
    UnsupportedPayloadMode,
    projector_service_read_policy,
)
from .policy import (
    CommandRegistry,
    PayloadGoldenVector,
    PayloadSchemaContract,
    PayloadSchemaRegistry,
    PayloadSchemaValidationError,
    UnknownCommandDefinition,
    UnknownPayloadSchema,
)
from .service import (
    AuthorizationReceipt,
    CommandService,
    CommittedCommandLookup,
    IdempotencyIdentityConflict,
    ObjectAdmissionLookup,
)
from .system import AuthorityEventSystem, open_authority_event_system
from .traceability import (
    INCREMENT_1A_TRACEABILITY,
    INCREMENT_1A2A_DEFERRED,
    INCREMENT_1A2A_TRACEABILITY,
)
from .types import (
    AggregateId,
    AggregateVersion,
    AuditId,
    AuthenticationContextId,
    AuthorizationDecisionId,
    CausationKind,
    CausationRef,
    CommandId,
    CorrelationId,
    EventId,
    ObjectAdmissionId,
    PayloadMode,
    RightsDecisionId,
    TemporalValue,
    TimePrecision,
    TrustScope,
    UtcTimestamp,
)

__all__ = [
    "AggregateId",
    "AggregateVersion",
    "AuditId",
    "AuthenticationContextId",
    "AuthenticationContextRecord",
    "AuthenticationError",
    "AuthenticationProof",
    "AuthorityCommands",
    "AuthorityEventSystem",
    "AuthorityEvents",
    "AuthorityPersistenceError",
    "AuthoritySchemaError",
    "AuthorityWriterBusy",
    "AuthorizationDecisionId",
    "AuthorizationDecisionRecord",
    "AuthorizationDenied",
    "AuthorizationReceipt",
    "AuthorizationRequestRecord",
    "CanonicalizationError",
    "CausationKind",
    "CausationRef",
    "CommandDefinition",
    "CommandDefinitionRecord",
    "CommandId",
    "CommandRegistry",
    "CommandResultRecord",
    "CommandService",
    "CommandValidationError",
    "CommittedCommand",
    "CommittedCommandIdentity",
    "CommittedCommandLookup",
    "CorrelationId",
    "EventId",
    "EventProvenanceRecord",
    "EventReadPolicy",
    "ExpectedVersionConflict",
    "INCREMENT_1A_TRACEABILITY",
    "INCREMENT_1A2A_DEFERRED",
    "INCREMENT_1A2A_TRACEABILITY",
    "IdempotencyConflict",
    "IdempotencyIdentityConflict",
    "InlinePayload",
    "LedgerEventRecord",
    "MetadataClass",
    "NO_PAYLOAD",
    "NoPayload",
    "ObjectAdmissionDescriptor",
    "ObjectAdmissionId",
    "ObjectAdmissionLookup",
    "ObjectAdmissionPayload",
    "PayloadGoldenVector",
    "PayloadId",
    "PayloadMode",
    "PayloadSchemaContract",
    "PayloadSchemaContractRecord",
    "PayloadSchemaRegistry",
    "PayloadSchemaValidationError",
    "ReadPolicyDenied",
    "RightsDecisionId",
    "SUCCESSFUL_READ_AUDIT_STATUS",
    "SemanticCommand",
    "StaticAuthenticator",
    "StaticAuthorizer",
    "StaticPrincipal",
    "TemporalValue",
    "TimePrecision",
    "TrustScope",
    "UnknownCausation",
    "UnknownCommandDefinition",
    "UnknownPayloadSchema",
    "UnsupportedPayloadMode",
    "UtcTimestamp",
    "canonical_json_bytes",
    "digest_bytes",
    "digest_canonical",
    "open_authority_event_system",
    "projector_service_read_policy",
    "validate_sha256_digest",
]
