"""Private proposal-only Graphiti adapter contracts.

Real Graphiti/model execution is deliberately disabled.  The public package
exports deterministic fake and approved replay implementations only.
"""

from .contracts import (
    GRAPHITI_ADAPTER_CONTRACT_VERSION,
    GRAPHITI_ADAPTER_POLICY_VERSION,
    GRAPHITI_WORKSPACE_POLICY_VERSION,
    QUALIFICATION_WORKSPACE_POLICY,
    REPLAY_WORKSPACE_POLICY,
    qualification_configuration,
    replay_configuration,
)
from .fake import DeterministicFakeGraphitiAdapter
from .models import (
    ApprovedReplayBundle,
    GraphitiAdapterConfiguration,
    GraphitiAdapterExecution,
    GraphitiAttemptRequest,
    GraphitiCleanupReceipt,
    GraphitiInputManifest,
    GraphitiManifestPassage,
    GraphitiReplaySource,
    GraphitiWorkspaceDescriptor,
    GraphitiWorkspacePolicy,
    REAL_GRAPHITI_RUNTIME_ENABLED,
    RealGraphitiRuntimeAuthority,
)
from .producer import GraphitiProposalProducerBridge
from .replay import ApprovedReplayGraphitiAdapter
from .types import (
    GraphitiAdapterConfigurationId,
    GraphitiAdapterContractError,
    GraphitiAdapterError,
    GraphitiAdapterOutcome,
    GraphitiAdapterReadPolicy,
    GraphitiAdapterStateError,
    GraphitiAttemptId,
    GraphitiCleanupReason,
    GraphitiCleanupReceiptId,
    GraphitiCredentialClass,
    GraphitiEgressPolicy,
    GraphitiExecutionProfile,
    GraphitiInputManifestId,
    GraphitiReplayEligibility,
    GraphitiReplayError,
    GraphitiReplaySourceId,
    GraphitiRuntimeMode,
    GraphitiRuntimeNotAuthorized,
    GraphitiWorkspaceError,
    GraphitiWorkspaceId,
    GraphitiWorkspacePolicyId,
    GraphitiWorkspaceState,
)
from .workspace import DisposableProposalWorkspace

__all__ = [
    "ApprovedReplayBundle",
    "ApprovedReplayGraphitiAdapter",
    "DeterministicFakeGraphitiAdapter",
    "DisposableProposalWorkspace",
    "GRAPHITI_ADAPTER_CONTRACT_VERSION",
    "GRAPHITI_ADAPTER_POLICY_VERSION",
    "GRAPHITI_WORKSPACE_POLICY_VERSION",
    "GraphitiAdapterConfigurationId",
    "GraphitiAdapterContractError",
    "GraphitiAdapterError",
    "GraphitiAdapterOutcome",
    "GraphitiAdapterReadPolicy",
    "GraphitiAdapterStateError",
    "GraphitiAttemptId",
    "GraphitiCleanupReason",
    "GraphitiCleanupReceiptId",
    "GraphitiCredentialClass",
    "GraphitiEgressPolicy",
    "GraphitiExecutionProfile",
    "GraphitiInputManifestId",
    "GraphitiReplayEligibility",
    "GraphitiReplayError",
    "GraphitiReplaySourceId",
    "GraphitiRuntimeMode",
    "GraphitiRuntimeNotAuthorized",
    "GraphitiWorkspaceError",
    "GraphitiWorkspaceId",
    "GraphitiWorkspacePolicyId",
    "GraphitiWorkspaceState",
    "GraphitiAdapterConfiguration",
    "GraphitiAdapterExecution",
    "GraphitiAttemptRequest",
    "GraphitiCleanupReceipt",
    "GraphitiInputManifest",
    "GraphitiManifestPassage",
    "GraphitiProposalProducerBridge",
    "GraphitiReplaySource",
    "GraphitiWorkspaceDescriptor",
    "GraphitiWorkspacePolicy",
    "QUALIFICATION_WORKSPACE_POLICY",
    "REAL_GRAPHITI_RUNTIME_ENABLED",
    "REPLAY_WORKSPACE_POLICY",
    "RealGraphitiRuntimeAuthority",
    "qualification_configuration",
    "replay_configuration",
]
