"""Private proposal-only Graphiti adapter contracts.

Public exports remain deterministic fake and approved replay. Real Graphiti
execution is EVALUATION-only when REAL_GRAPHITI_RUNTIME_ENABLED is True.
"""

from .admission import (
    ADMITTED_NEO4J_LABELS,
    ADMITTED_OD006_VECTOR_DIMENSIONS,
    AdmittedGraphitiProjectorWrite,
    GRAPHITI_ADMITTED_PROJECTOR_FAMILY_ID,
    GraphitiProposalAdmissionAction,
    GraphitiProposalAdmissionDecision,
    GraphitiProposalAdmissionDecisionId,
    GraphitiProposalAdmissionError,
    admit_graphiti_proposals_for_projectors,
    increment4_batches_for_admitted_graphiti,
    require_admitted_projector_write,
)
from .contracts import (
    GRAPHITI_ADAPTER_CONTRACT_VERSION,
    GRAPHITI_ADAPTER_POLICY_VERSION,
    GRAPHITI_WORKSPACE_POLICY_VERSION,
    QUALIFICATION_WORKSPACE_POLICY,
    REPLAY_WORKSPACE_POLICY,
    qualification_configuration,
    replay_configuration,
)
from .fake import DeterministicFakeGraphitiAdapter
from .models import (
    ApprovedReplayBundle,
    GraphitiAdapterConfiguration,
    GraphitiAdapterConfigurationRecord,
    GraphitiAdapterExecution,
    GraphitiAttemptRecord,
    GraphitiAttemptRequest,
    GraphitiCleanupReceipt,
    GraphitiInputManifest,
    GraphitiManifestPassage,
    GraphitiReplayApprovalRequest,
    GraphitiReplaySource,
    GraphitiReplaySourceRecord,
    GraphitiWorkspaceDescriptor,
    GraphitiWorkspacePolicy,
    REAL_GRAPHITI_RUNTIME_ENABLED,
    RealGraphitiRuntimeAuthority,
)
from .producer import GraphitiProposalProducerBridge
from .replay import ApprovedReplayGraphitiAdapter
from .traceability import (
    GraphitiAdapterTraceabilityRow,
    INCREMENT_4D_ADR_ANCHORS,
    INCREMENT_4D_DEFERRED,
    INCREMENT_4D_EXCLUSIONS,
    INCREMENT_4D_TRACEABILITY,
)
from .types import (
    GraphitiAdapterConfigurationId,
    GraphitiAdapterContractError,
    GraphitiAdapterAmbiguousEffect,
    GraphitiAdapterError,
    GraphitiAdapterIdentifierReuse,
    GraphitiAdapterOutcome,
    GraphitiAdapterRightsDenied,
    GraphitiAdapterSemanticCollision,
    GraphitiAdapterReadPolicy,
    GraphitiAdapterStateError,
    GraphitiAdapterVersionConflict,
    GraphitiAttemptId,
    GraphitiCleanupReason,
    GraphitiCleanupReceiptId,
    GraphitiCredentialClass,
    GraphitiEgressPolicy,
    GraphitiExecutionProfile,
    GraphitiInputManifestId,
    GraphitiReplayEligibility,
    GraphitiReplayError,
    GraphitiReplaySourceId,
    GraphitiRuntimeMode,
    GraphitiRuntimeNotAuthorized,
    GraphitiWorkspaceError,
    GraphitiWorkspaceId,
    GraphitiWorkspacePolicyId,
    GraphitiWorkspaceState,
)
from .workspace import DisposableProposalWorkspace

__all__ = [
    "ADMITTED_NEO4J_LABELS",
    "ADMITTED_OD006_VECTOR_DIMENSIONS",
    "AdmittedGraphitiProjectorWrite",
    "ApprovedReplayBundle",
    "ApprovedReplayGraphitiAdapter",
    "DeterministicFakeGraphitiAdapter",
    "GRAPHITI_ADMITTED_PROJECTOR_FAMILY_ID",
    "DisposableProposalWorkspace",
    "GRAPHITI_ADAPTER_CONTRACT_VERSION",
    "GRAPHITI_ADAPTER_POLICY_VERSION",
    "GRAPHITI_WORKSPACE_POLICY_VERSION",
    "GraphitiAdapterAmbiguousEffect",
    "GraphitiAdapterConfigurationId",
    "GraphitiAdapterContractError",
    "GraphitiAdapterError",
    "GraphitiAdapterIdentifierReuse",
    "GraphitiAdapterOutcome",
    "GraphitiAdapterRightsDenied",
    "GraphitiAdapterSemanticCollision",
    "GraphitiAdapterReadPolicy",
    "GraphitiAdapterStateError",
    "INCREMENT_4D_TRACEABILITY",
    "INCREMENT_4D_EXCLUSIONS",
    "INCREMENT_4D_DEFERRED",
    "INCREMENT_4D_ADR_ANCHORS",
    "GraphitiAdapterTraceabilityRow",
    "GraphitiAdapterVersionConflict",
    "GraphitiAttemptId",
    "GraphitiCleanupReason",
    "GraphitiCleanupReceiptId",
    "GraphitiCredentialClass",
    "GraphitiEgressPolicy",
    "GraphitiExecutionProfile",
    "GraphitiInputManifestId",
    "GraphitiReplayEligibility",
    "GraphitiReplayError",
    "GraphitiReplaySourceId",
    "GraphitiRuntimeMode",
    "GraphitiRuntimeNotAuthorized",
    "GraphitiWorkspaceError",
    "GraphitiWorkspaceId",
    "GraphitiWorkspacePolicyId",
    "GraphitiWorkspaceState",
    "GraphitiAdapterConfiguration",
    "GraphitiAdapterConfigurationRecord",
    "GraphitiAdapterExecution",
    "GraphitiAttemptRecord",
    "GraphitiAttemptRequest",
    "GraphitiCleanupReceipt",
    "GraphitiInputManifest",
    "GraphitiManifestPassage",
    "GraphitiProposalAdmissionAction",
    "GraphitiProposalAdmissionDecision",
    "GraphitiProposalAdmissionDecisionId",
    "GraphitiProposalAdmissionError",
    "GraphitiProposalProducerBridge",
    "GraphitiReplayApprovalRequest",
    "GraphitiReplaySource",
    "GraphitiReplaySourceRecord",
    "GraphitiWorkspaceDescriptor",
    "GraphitiWorkspacePolicy",
    "QUALIFICATION_WORKSPACE_POLICY",
    "REAL_GRAPHITI_RUNTIME_ENABLED",
    "REPLAY_WORKSPACE_POLICY",
    "RealGraphitiRuntimeAuthority",
    "admit_graphiti_proposals_for_projectors",
    "increment4_batches_for_admitted_graphiti",
    "qualification_configuration",
    "replay_configuration",
    "require_admitted_projector_write",
]
